
export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    FORGETPASS_REQUEST:'FORGETPASS_REQUEST',
    FORGETPASS_SUCCESS:'FORGETPASS_SUCCESS',
    FORGETPASS_FAILURE:'FORGETPASS_FAILURE',
    RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE:'RESET_PASSWORD_FAILURE',
}

export const userConstants = {
    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILURE:'SIGNUP_FAILURE'
}

export const productConstants = {
    PRODUCT_REQUEST:'PRODUCT_REQUEST',
    PRODUCT_SUCCESS:'PRODUCT_SUCCESS',
    PRODUCT_FAILURE:'PRODUCT_FAILURE',
    SEARCH_PRODUCT_REQUEST:'SEARCH_PRODUCT_REQUEST',
    SEARCH_PRODUCT_SUCCESS:'SEARCH_PRODUCT_SUCCESS',
    SEARCH_PRODUCT_FAILURE:'SEARCH_PRODUCT_FAILURE',
    PRODUCT_DETAIL_REQUEST:'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS:'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILURE:'PRODUCT_DETAIL_FAILURE'
}

export const cartConstants = {
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    RESET_CART: 'RESET_CART',
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE"
}
