
export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    FORGETPASS_REQUEST:'FORGETPASS_REQUEST',
    FORGETPASS_SUCCESS:'FORGETPASS_SUCCESS',
    FORGETPASS_FAILURE:'FORGETPASS_FAILURE',
    RESETPASS_REQUEST:'RESETPASS_REQUEST',
    RESETPASS_SUCCESS:'RESETPASS_SUCCESS',
    RESETPASS_FAILURE:'RESETPASS_FAILURE',
}
